/* Related Blog Posts */
var RelatedBlog,ShowRePosts;!function(a,l){var e,h={nameWid:"",numberOfposts:8,summaryLength:370,titleLength:"auto",thumbnailSize:200,containerId:"RelatedPosts",newTabLink:!1,moreText:"",callBack:function(){}};for(e in relatedPostConfig)h[e]=("undefined"==relatedPostConfig[e]?h:relatedPostConfig)[e];function n(e){var t=a.createElement("script");t.type="text/javascript",t.src=e,l.appendChild(t)}function A(e){var t,a,l=e.length;if(0===l)return!1;for(;--l;)t=Math.floor(Math.random()*(l+1)),a=e[l],e[l]=e[t],e[t]=a;return e}var i="object"==typeof labelArray&&0<labelArray.length?"/-/"+A(labelArray)[0]:"";RelatedBlog=function(e){var t=e.feed.openSearch$totalResults.$t-h.numberOfposts,e=(e=1,t=0<t?t:1,Math.floor(Math.random()*(t-e+1))+e);n(h.homePage.replace(/\/?\?m=\d+(\&|$)|\/+$/,"")+"/feeds/posts/summary"+i+"?alt=json-in-script&orderby=updated&start-index="+e+"&max-results="+h.numberOfposts+"&callback=ShowRePosts")},ShowRePosts=function(e){var t,a,l,n,i=document.getElementById(h.containerId),r=A(e.feed.entry),s=h.widgetStyle,o=h.nameWid+'<ul class="RelatedPosts-mode-'+s+'">',d=h.newTabLink?' target="_blank"':"",m='<span style="display:block;clear:both;"></span>';if(xx='<span class="loading-img"></span>',i){for(var c=0;c<h.numberOfposts&&c!=r.length;c++){a=r[c].title.$t,l="auto"!==h.titleLength&&h.titleLength<a.length?a.substring(0,h.titleLength)+"…":a,n="media$thumbnail"in r[c]&&!1!==h.thumbnailSize?r[c].media$thumbnail.url.replace(/\/s\d+(\-c)?/,"/w"+h.thumbnailSize+""):h.noImage,"summary"in r[c]&&0<h.summaryLength&&r[c].summary.$t.replace(/<br ?\/?>/g," ").replace(/<.*?>/g,"").replace(/[<>]/g,"").substring(0,h.summaryLength);for(var g=0,u=r[c].link.length;g<u;g++)t="alternate"==r[c].link[g].rel?r[c].link[g].href:"#";


o += 3 == s ? '<li class="RelatedPosts-item" tabindex="0"><a class="Relatedtitleimg" href="' + t + '"' + d + ' title="' + a + '"><img alt="' + a + '" class="relatedPost-img DT-lazy" data-src="' + n + '" width="' + h.thumbnailSize + '" height="' + h.thumbnailSize + '" title="' + a + '"><span class="loading-img"></span></a><div class="Relateditem"><a class="Relatedtitle" title="' + a + '" href="' + t + '"' + d + ">" + l + "</a></div>" + m + '<span class="DtVIEWS EntryVi HideViews" data-add="true" data-view="0" expr:data-id="data:post.id" /></li>' : '<li><a title="' + a + '" href="' + t + '"' + d + ">" + l + "</a></li>";



}i.innerHTML=o+="</ul>"+m,h.callBack()}},n(h.homePage.replace(/\/?\?m=\d+(\&|$)|\/+$/,"")+"/feeds/posts/summary"+i+"?alt=json-in-script&orderby=updated&max-results=0&callback=RelatedBlog")}((window,document),document.getElementsByTagName("head")[0]);
